export const dynamic = "force-static";

export default function PrivacyPolicyPage() {
  return (
    <main className="container max-w-3xl py-12">
      <h1 className="text-3xl font-bold">Privacy Policy</h1>
      <p className="mt-3 text-muted-foreground">Last updated: April 6, 2026</p>

      <section className="prose prose-neutral dark:prose-invert mt-8 max-w-none">
        <p>
          This Privacy Policy explains how <b>exempliphai</b> ("we", "us", "our") collects, uses,
          and shares information when you use our website, services, and browser extension
          (collectively, the "Services").
        </p>

        <h2>Summary</h2>
        <ul>
          <li>We collect account and usage data to operate the Services.</li>
          <li>
            If you choose to use AI features, we process the text you provide to generate outputs.
          </li>
          <li>
            We store job-application tracking data (e.g., applied jobs, autofills, custom answers)
            in your account to provide dashboards and sync.
          </li>
          <li>
            We do not sell your personal information.
          </li>
        </ul>

        <h2>Information We Collect</h2>
        <h3>Information you provide</h3>
        <ul>
          <li>
            <b>Account information</b> (e.g., phone number for sign-in, user identifiers).
          </li>
          <li>
            <b>Profile information</b> you enter in the extension (name, email, links, work history, etc.).
          </li>
          <li>
            <b>Documents</b> you upload (e.g., resume, cover letter) and derived metadata.
          </li>
          <li>
            <b>AI inputs</b> (prompts, form questions) and <b>AI outputs</b> (generated answers) when you use AI features.
          </li>
        </ul>

        <h3>Information collected automatically</h3>
        <ul>
          <li>
            <b>Usage and diagnostics</b> (feature usage, errors, performance signals).
          </li>
          <li>
            <b>Job application telemetry</b> generated by the extension (e.g., application URLs,
            domains, timestamps, and aggregated counters).
          </li>
        </ul>

        <h2>How We Use Information</h2>
        <ul>
          <li>Provide and maintain the Services (sync, dashboards, billing, support).</li>
          <li>Generate AI-assisted outputs you request (resume tailoring, custom answers, etc.).</li>
          <li>Improve reliability and prevent abuse/fraud.</li>
          <li>Comply with legal obligations.</li>
        </ul>

        <h2>How We Share Information</h2>
        <p>
          We share information only as needed to provide the Services, including:
        </p>
        <ul>
          <li>
            <b>Service providers</b> (e.g., hosting, analytics, payments) who process data on our behalf.
          </li>
          <li>
            <b>AI providers</b> when you use AI features. We send the minimal necessary input to generate
            the output you requested.
          </li>
          <li>
            <b>Legal</b> if required to comply with law or protect rights and safety.
          </li>
        </ul>

        <h2>Data Retention</h2>
        <p>
          We retain data as long as needed to provide the Services and for legitimate business purposes
          (e.g., compliance, dispute resolution). You may request deletion as described below.
        </p>

        <h2>Your Choices</h2>
        <ul>
          <li>
            You can sign out of the extension and website.
          </li>
          <li>
            You can choose whether to use AI features.
          </li>
          <li>
            You can request access, correction, or deletion of your account data by contacting us.
          </li>
        </ul>

        <h2>Security</h2>
        <p>
          We use reasonable administrative, technical, and organizational safeguards to protect
          information. No method of transmission or storage is 100% secure.
        </p>

        <h2>Children</h2>
        <p>
          The Services are not intended for children under 13 (or the minimum age required in your
          jurisdiction). We do not knowingly collect data from children.
        </p>

        <h2>Contact</h2>
        <p>
          Questions or requests: <a href="mailto:support@exempliph.ai">support@exempliph.ai</a>
        </p>
      </section>
    </main>
  );
}
